process = {
    version: 'v18.16.1',
    versions: {
      node: '18.16.1',
      acorn: '8.8.2',
      ada: '1.0.4',
      ares: '1.19.1',
      brotli: '1.0.9',
      cldr: '42.0',
      icu: '72.1',
      llhttp: '6.0.11',
      modules: '108',
      napi: '8',
      nghttp2: '1.52.0',
      nghttp3: '0.7.0',
      ngtcp2: '0.8.1',
      openssl: '3.0.9+quic',
      simdutf: '3.2.2',
      tz: '2022g',
      undici: '5.21.0',
      unicode: '15.0',
      uv: '1.44.2',
      uvwasi: '0.0.15',
      v8: '10.2.154.26-node.26',
      zlib: '1.2.13'
    },
    arch: 'arm64',
    platform: 'darwin',
    release: {
      name: 'node',
      lts: 'Hydrogen',
      sourceUrl: 'https://nodejs.org/download/release/v18.16.1/node-v18.16.1.tar.gz',
      headersUrl: 'https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz'
    },
    _rawDebug: [Function: _rawDebug],
    moduleLoadList: [
      'Internal Binding builtins',
      'Internal Binding errors',
      'Internal Binding util',
      'NativeModule internal/errors',
      'Internal Binding config',
      'Internal Binding timers',
      'Internal Binding async_wrap',
      'Internal Binding constants',
      'Internal Binding types',
      'NativeModule internal/util',
      'NativeModule internal/util/types',
      'NativeModule internal/validators',
      'NativeModule internal/promise_hooks',
      'Internal Binding task_queue',
      'Internal Binding symbols',
      'NativeModule internal/async_hooks',
      'NativeModule internal/linkedlist',
      'NativeModule internal/priority_queue',
      'NativeModule internal/assert',
      'Internal Binding icu',
      'NativeModule internal/util/inspect',
      'NativeModule internal/util/debuglog',
      'NativeModule internal/timers',
      'NativeModule events',
      'Internal Binding buffer',
      'Internal Binding string_decoder',
      'NativeModule internal/buffer',
      'Internal Binding blob',
      'NativeModule internal/encoding',
      'Internal Binding messaging',
      'NativeModule internal/worker/js_transferable',
      'NativeModule internal/constants',
      'NativeModule internal/blob',
      'NativeModule internal/file',
      'NativeModule buffer',
      'NativeModule internal/modules/esm/handle_process_exit',
      'Internal Binding process_methods',
      'NativeModule internal/process/per_thread',
      'Internal Binding credentials',
      'NativeModule internal/process/promises',
      'NativeModule internal/fixed_queue',
      'NativeModule async_hooks',
      'NativeModule internal/process/task_queues',
      'Internal Binding worker',
      'NativeModule internal/util/parse_args/utils',
      'NativeModule internal/util/parse_args/parse_args',
      'NativeModule internal/mime',
      'NativeModule util',
      'Internal Binding performance',
      'NativeModule internal/perf/utils',
      'NativeModule internal/event_target',
      'NativeModule timers',
      'NativeModule internal/abort_controller',
      'NativeModule internal/streams/utils',
      'NativeModule internal/streams/end-of-stream',
      'NativeModule internal/streams/destroy',
      'NativeModule internal/streams/legacy',
      'NativeModule internal/streams/add-abort-signal',
      'NativeModule internal/streams/buffer_list',
      'NativeModule internal/streams/state',
      'NativeModule string_decoder',
      'NativeModule internal/streams/from',
      'NativeModule internal/streams/readable',
      'NativeModule internal/streams/writable',
      'NativeModule internal/streams/duplex',
      'NativeModule internal/streams/pipeline',
      'NativeModule internal/streams/compose',
      'NativeModule internal/streams/operators',
      'NativeModule stream/promises',
      'NativeModule internal/streams/transform',
      'NativeModule internal/streams/passthrough',
      'NativeModule stream',
      'NativeModule internal/worker/io',
      'NativeModule internal/structured_clone',
      'Internal Binding trace_events',
      'NativeModule path',
      'NativeModule internal/process/execution',
      'NativeModule internal/process/warning',
      'Internal Binding fs',
      'NativeModule internal/querystring',
      'NativeModule querystring',
      'Internal Binding url',
      'NativeModule internal/url',
      'NativeModule internal/fs/utils',
      'Internal Binding fs_dir',
      'NativeModule internal/fs/dir',
      'Internal Binding fs_event_wrap',
      'Internal Binding uv',
      'NativeModule internal/fs/watchers',
      'NativeModule internal/fs/read_file_context',
      'NativeModule fs',
      'Internal Binding serdes',
      'Internal Binding mksnapshot',
      'NativeModule internal/v8/startup_snapshot',
      'Internal Binding profiler',
      'Internal Binding heap_utils',
      'Internal Binding stream_wrap',
      'NativeModule internal/stream_base_commons',
      'NativeModule internal/heap_utils',
      'Internal Binding options',
      ... 97 more items
    ],
    binding: [Function: binding],
    _linkedBinding: [Function: _linkedBinding],
    _events: [Object: null prototype] {
      newListener: [Function: startListeningIfSignal],
      removeListener: [Function: stopListeningIfSignal],
      warning: [Function: onWarning],
      exit: [Function: handleProcessExit],
      SIGWINCH: [Function: refreshStdoutOnSigWinch]
    },
    _eventsCount: 5,
    _maxListeners: undefined,
    domain: null,
    _exiting: [Getter/Setter],
    config: [Getter/Setter],
    dlopen: [Function: dlopen],
    uptime: [Function: uptime],
    _getActiveRequests: [Function: _getActiveRequests],
    _getActiveHandles: [Function: _getActiveHandles],
    getActiveResourcesInfo: [Function: getActiveResourcesInfo],
    reallyExit: [Function: reallyExit],
    _kill: [Function: _kill],
    cpuUsage: [Function: cpuUsage],
    resourceUsage: [Function: resourceUsage],
    memoryUsage: [Function: memoryUsage] { rss: [Function: rss] },
    constrainedMemory: [Function: constrainedMemory],
    kill: [Function: kill],
    exit: [Function: exit],
    hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
    openStdin: [Function (anonymous)],
    getuid: [Function: getuid],
    geteuid: [Function: geteuid],
    getgid: [Function: getgid],
    getegid: [Function: getegid],
    getgroups: [Function: getgroups],
    allowedNodeEnvironmentFlags: [Getter/Setter],
    assert: [Function: deprecated],
    features: {
      inspector: true,
      debug: false,
      uv: true,
      ipv6: true,
      tls_alpn: true,
      tls_sni: true,
      tls_ocsp: true,
      tls: true,
      cached_builtins: [Getter]
    },
    _fatalException: [Function (anonymous)],
    setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback],
    hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
    emitWarning: [Function: emitWarning],
    nextTick: [Function: nextTick],
    _tickCallback: [Function: runNextTicks],
    _debugProcess: [Function: _debugProcess],
    _debugEnd: [Function: _debugEnd],
    _startProfilerIdleNotifier: [Function (anonymous)],
    _stopProfilerIdleNotifier: [Function (anonymous)],
    stdout: [Getter],
    stdin: [Getter],
    stderr: [Getter],
    abort: [Function: abort],
    umask: [Function: wrappedUmask],
    chdir: [Function: wrappedChdir],
    cwd: [Function: wrappedCwd],
    initgroups: [Function: initgroups],
    setgroups: [Function: setgroups],
    setegid: [Function (anonymous)],
    seteuid: [Function (anonymous)],
    setgid: [Function (anonymous)],
    setuid: [Function (anonymous)],
    env: {
      LOCAL_GIT_DIRECTORY: '/Applications/GitHub Desktop.app/Contents/Resources/app/git',
      MallocNanoZone: '0',
      USER: 'abudouwayitiparouke',
      SECURITYSESSIONID: '186ab',
      COMMAND_MODE: 'unix2003',
      __CFBundleIdentifier: 'com.microsoft.VSCode',
      PATH: '/Users/rock/.nvm/versions/node/v18.16.1/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/rock/Library/pnpm:/Users/rock/.nvm/versions/node/v18.16.1/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/rock/.local/bin:/Users/rock/.local/bin:/Users/rock/.local/bin',
      LOGNAME: 'abudouwayitiparouke',
      SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.tHASytb9By/Listeners',
      HOME: '/Users/rock',
      SHELL: '/bin/zsh',
      ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
      TMPDIR: '/var/folders/9n/q0bltm4d3nbdh5b6s5qspfj80000gn/T/',
      LaunchInstanceID: '132095FC-0FD1-4920-B738-65B3465E46A3',
      __CF_USER_TEXT_ENCODING: '0x1F5:0x19:0x34',
      XPC_SERVICE_NAME: '0',
      XPC_FLAGS: '0x0',
      PWD: '/Users/rock/projects/public/node-project-creator',
      NVM_DIR: '/Users/rock/.nvm',
      HOMEBREW_PREFIX: '/opt/homebrew',
      INFOPATH: '/opt/homebrew/share/info:/opt/homebrew/share/info:',
      MANPATH: '/Users/rock/.nvm/versions/node/v18.16.1/share/man:/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/Users/rock/.nvm/versions/node/v18.16.1/share/man:/opt/homebrew/share/man::',
      LANG: 'zh_CN.UTF-8',
      LS_COLORS: 'di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43',
      TERM: 'xterm-256color',
      NVM_CD_FLAGS: '-q',
      PAGER: 'less',
      TERM_PROGRAM_VERSION: '1.85.1',
      HOMEBREW_REPOSITORY: '/opt/homebrew',
      SHLVL: '3',
      HOMEBREW_CELLAR: '/opt/homebrew/Cellar',
      TERM_SESSION_ID: 'D200DFAC-4F28-41C6-B544-5533FA6D2C8C',
      ZSH: '/Users/rock/.oh-my-zsh',
      LESS: '-R',
      _P9K_SSH_TTY: '/dev/ttys087',
      _P9K_TTY: '/dev/ttys087',
      NVM_BIN: '/Users/rock/.nvm/versions/node/v18.16.1/bin',
      P9K_TTY: 'old',
      NVM_INC: '/Users/rock/.nvm/versions/node/v18.16.1/include/node',
      PNPM_HOME: '/Users/rock/Library/pnpm',
      TERM_PROGRAM: 'vscode',
      LSCOLORS: 'Gxfxcxdxbxegedabagacad',
      COLORTERM: 'truecolor',
      GIT_ASKPASS: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh',
      VSCODE_GIT_ASKPASS_NODE: '/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)',
      VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
      VSCODE_GIT_ASKPASS_MAIN: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js',
      VSCODE_GIT_IPC_HANDLE: '/var/folders/9n/q0bltm4d3nbdh5b6s5qspfj80000gn/T/vscode-git-8a91f81440.sock',
      VSCODE_INJECTION: '1',
      VSCODE_NONCE: 'b3c0dce4-70ff-44eb-8499-24814bc5b41a',
      ZDOTDIR: '/Users/rock',
      USER_ZDOTDIR: '/Users/rock',
      OLDPWD: '/Users/rock/projects/public/node-project-creator',
      P9K_SSH: '0',
      https_proxy: 'http://127.0.0.1:7890',
      http_proxy: 'http://127.0.0.1:7890',
      all_proxy: 'socks5://127.0.0.1:7890',
      _: '/Users/rock/.nvm/versions/node/v18.16.1/bin/npc'
    },
    title: 'node',
    argv: [
      '/Users/rock/.nvm/versions/node/v18.16.1/bin/node',
      '/Users/rock/.nvm/versions/node/v18.16.1/bin/npc',
      'create',
      'react-app'
    ],
    execArgv: [],
    pid: 69070,
    ppid: 30518,
    execPath: '/Users/rock/.nvm/versions/node/v18.16.1/bin/node',
    debugPort: 9229,
    argv0: 'node',
    exitCode: undefined,
    _preload_modules: [],
    report: [Getter],
    setSourceMapsEnabled: [Function: setSourceMapsEnabled],
    [Symbol(kCapture)]: false
  }